---
- name: running system_lvm tasks
  block:
    - name: creating/resizing volume group
      community.general.lvg:
        pesize: "{{ item['value']['pesize'] | default(omit) }}"
        pv_options: "{{ item['value']['pv_options'] | default(omit) }}"
        pvresize: "{{ item['value']['pvresize'] | default(omit) }}"
        pvs: "{{ item['value']['pvs'] }}"
        state: present
        vg: "{{ item['value']['vg'] }}"
        vg_options:  "{{ item['value']['vg_options'] | default(omit) }}"
      loop: "{{ system_lvm | dict2items }}"
      when:
        - item['value']['vg'] is defined
        - item['value']['pvs'] is defined
        - item['value']['state'] is defined and 
          item['value']['state'] == "present" or
          item['value']['state'] is undefined   

    - name: removing volume group
      community.general.lvg:
        force: "{{ item['value']['force'] | default(omit) }}"
        state: absent
        vg: "{{ item['value'][vg] }}"
      loop:
        "{{ system_lvm | dict2items }}"
      when:
        - item['value']['vg'] is defined
        - item['value']['state'] is defined
        - item['value']['state'] == absent
  when:
    system_lvm is defined
