---
- name: running system_lvm tasks
  include_tasks: system_lvm.yml
  loop: "{{ system_lvm | dict2items }}"
  loop_control:
    label: "{{ system_lvm_item['key'] }}"
    loop_var: system_lvm_item
  when:
    system_lvm is defined
