---
- name: running system_lvm tasks
  block:
    - name: creating/resizing volume group
      community.general.lvg:
        pesize: "{{ item['value']['pesize'] | default(omit) }}"
        pv_options: "{{ item['value']['pv_options'] | default(omit) }}"
        pvresize: "{{ item['value']['pvresize'] | default(omit) }}"
        pvs: "{{ item['value']['pvs'] }}"
        state: present
        vg: "{{ item['value']['vg'] }}"
        vg_options:  "{{ item['value']['vg_options'] | default(omit) }}"
      loop: "{{ system_lvm | dict2items }}"
      when:
        - item['value']['pvs'] is defined
        - item['value']['state'] is defined and 
          item['value']['state'] == "present" or
          item['value']['state'] is undefined   
        - item['value']['vg'] is defined

    - name: creating/resizing logical volume
      community.general.lvol:
        active: "{{ item[1]['active'] | default(omit) }}"
        force: "{{ item[1]['force'] | default(omit) }}"
        lv: "{{ item[1]['lv'] | default(omit) }}"
        opts: "{{ item[1]['opts'] | default(omit) }}"
        pvs: "{{ item[1]['pvs'] | default(omit) }}"
        resizefs: "{{ item[1]['resizefs'] | default(omit) }}"
        shrink: "{{ item[1]['shrink'] | default(omit) }}"
        size: "{{ item[1]['size'] }}"
        snapshot: "{{ item[1]['snapshot'] | default(omit) }}"
        state: present
        thinpool: "{{ item[1]['thinpool'] | default(omit) }}"
        vg: "{{ item[0]['vg'] }}"
      loop:
        "{{ system_lvm | subelements('lv') }}"
      loop_conttrol:
        label: "{{ item[0]['vg'], item[1]['lv'] }}"
      when:
        - item[0]['vg'] is defined
        - item[1]['size'] is defined
        - item[1]['state'] is defined and 
          item[1]['state'] == "present" or
          item[1]['state'] is undefined   
        

    - name: removing logical volume
      community.general.lvol:
        force: "{{ item[1]['force'] | default(omit) }}"
        lv: "{{ item[1]['lv'] }}"
        state: absent
        vg: "{{ item[0]['vg'] }}"
      loop:
        "{{ system_lvm | subelements('lv') }}"
      loop_conttrol:
        label: "{{ item[0]['vg'], item[1]['lv'] }}"
      when:
        - item[0]['vg'] is defined
        - item[1]['state'] is defined
        - item[1]['state'] == "absent"

    - name: removing volume group
      community.general.lvg:
        force: "{{ item['value']['force'] | default(omit) }}"
        state: absent
        vg: "{{ item['value']['vg'] }}"
      loop:
        "{{ system_lvm | dict2items }}"
      when:
        - item['value']['state'] is defined
        - item['value']['state'] == absent
        - item['value']['vg'] is defined
  when:
    system_lvm is defined
